(()=>{
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const KEYS=window.FAKEBOT2_KEYS,SCALES=window.FAKEBOT2_SCALES,INSTR=window.FAKEBOT2_INSTRUMENTS;
const state={mode:"perform",key:0,scale:"Minor",inst:INSTR[0].id,tempo:96,score:0,streak:0,loop:false,loopNotes:[],target:[],targetIndex:0,last:[],mutate:0};
let ctx,master,delay,fb,filter,loopTimer=null,sampleCache=new Map();
const E={pads:$("#pads"),readout:$("#readout"),score:$("#score"),targetText:$("#targetText"),targetDots:$("#targetDots"),keySel:$("#keySel"),scaleSel:$("#scaleSel"),instSel:$("#instSel"),tempo:$("#tempo"),play:$("#playBtn"),reply:$("#replyBtn"),mutate:$("#mutateBtn"),newGame:$("#newGameBtn"),panic:$("#panicBtn")};
function midiFreq(n){return 440*Math.pow(2,(n-69)/12)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function pick(a){return a[Math.floor(Math.random()*a.length)]}function inst(){return INSTR.find(x=>x.id===state.inst)||INSTR[0]}function scaleNotes(){return SCALES[state.scale]||SCALES.Minor}function degreeMidi(i,oct=4){const sc=scaleNotes();const d=((i%sc.length)+sc.length)%sc.length;const o=Math.floor(i/sc.length);return 12*(oct+1+o)+state.key+sc[d]}function noteName(m){return KEYS[((m%12)+12)%12]+Math.floor(m/12-1)}function padMidis(){return $$(".pad").map(p=>Number(p.dataset.midi)).filter(Number.isFinite)}
async function audio(){if(ctx)return;ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=.78;filter=ctx.createBiquadFilter();filter.type="lowpass";filter.frequency.value=11000;delay=ctx.createDelay(.7);delay.delayTime.value=.18;fb=ctx.createGain();fb.gain.value=.22;delay.connect(fb);fb.connect(delay);filter.connect(master);filter.connect(delay);delay.connect(master);master.connect(ctx.destination)}
function curve(g,t,d,peak){g.gain.cancelScheduledValues(t);g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(peak,t+.012);g.gain.exponentialRampToValueAtTime(0.0001,t+d)}
function bitCrusher(node,bits=8){if(!ctx||bits>=10)return node;const sh=ctx.createWaveShaper();const steps=Math.pow(2,bits);const c=new Float32Array(65536);for(let i=0;i<c.length;i++){const x=i/(c.length-1)*2-1;c[i]=Math.round(x*steps)/steps}sh.curve=c;node.connect(sh);return sh}
function pulseWave(duty=.5){const n=2048,real=new Float32Array(n),imag=new Float32Array(n);for(let k=1;k<n;k++){imag[k]=2/(Math.PI*k)*Math.sin(Math.PI*k*duty)}return ctx.createPeriodicWave(real,imag,{disableNormalization:false})}
function playChip(m,vel=.85,when=0,dur=.7){const it=inst();const t=(ctx?.currentTime||0)+when;const out=ctx.createGain();out.gain.value=1;let srcNodes=[];const f=midiFreq(m+(it.octave||0)*12);const mkOsc=(type,det=0)=>{const o=ctx.createOscillator();if(type==="pulse")o.setPeriodicWave(pulseWave(it.duty??.5));else if(type==="organ"){o.type="triangle"}else o.type=type||"triangle";o.frequency.value=f*(1+det);return o};if(it.wave==="fm"){const car=ctx.createOscillator(),mod=ctx.createOscillator(),mg=ctx.createGain();car.type="sine";mod.type="sine";car.frequency.value=f;mod.frequency.value=f*(it.fmRatio||2);mg.gain.value=f*(it.modIndex||1.4);mod.connect(mg);mg.connect(car.frequency);car.connect(out);srcNodes=[car,mod]}else if(it.wave==="saw"){const a=mkOsc("sawtooth",it.detune||0),b=mkOsc("sawtooth",-(it.detune||.004));a.connect(out);b.connect(out);srcNodes=[a,b]}else if(it.wave==="organ"){[1,2,3].forEach((r,i)=>{const o=mkOsc(i?"sine":"triangle");o.frequency.value=f*r;o.connect(out);srcNodes.push(o)})}else{const o=mkOsc(it.wave==="pulse"?"pulse":it.wave||"triangle");o.connect(out);srcNodes=[o]}let final=bitCrusher(out,it.bitDepth||12);const amp=ctx.createGain();final.connect(amp);amp.connect(filter);const d=dur*(it.decay||.8)*(it.pluck?.75:1);curve(amp,t,clamp(d,.12,2.3),(it.gain||.35)*vel);srcNodes.forEach(o=>{o.start(t);o.stop(t+d+.04)})}
async function loadSample(it){if(sampleCache.has(it.url))return sampleCache.get(it.url);await audio();const res=await fetch(it.url);const arr=await res.arrayBuffer();const buf=await ctx.decodeAudioData(arr);sampleCache.set(it.url,buf);return buf}
async function playSample(m,vel=.8,when=0){const it=inst();try{const buf=await loadSample(it);const t=ctx.currentTime+when;const s=ctx.createBufferSource();const g=ctx.createGain();s.buffer=buf;s.playbackRate.value=Math.pow(2,(m-(it.root||72))/12);g.gain.value=(it.gain||.6)*vel;s.connect(g);g.connect(filter);s.start(t);s.stop(t+Math.min(1.4,buf.duration+.1))}catch{playChip(m,vel,when,.45)}}
async function playNote(m,vel=.85,when=0,dur=.65){await audio();if(ctx.state==="suspended")await ctx.resume();const it=inst();if(it.kind==="sample")playSample(m,vel,when);else playChip(m,vel,when,dur)}
function patternText(p){return p.map(noteName).join(" · ")}function setReadout(s){E.readout.textContent=s}function syncScore(){E.score.textContent=`score ${state.score} · streak ${state.streak}`}function syncTargetDots(){E.targetDots.innerHTML="";state.target.forEach((_,i)=>{const d=document.createElement("div");d.className="dot"+(i<state.targetIndex?" done":i===state.targetIndex?" now":"");E.targetDots.appendChild(d)})}
function makePads(){E.pads.innerHTML="";const color=inst().color;for(let i=0;i<16;i++){const m=degreeMidi(i-3, i<4?3:4);const b=document.createElement("button");b.className="pad";b.dataset.midi=m;b.dataset.degree=i-3;b.style.setProperty("--padColor",color);b.innerHTML=`<span>${noteName(m)}</span>`;const down=ev=>{ev.preventDefault();hitPad(b,m,true)};b.addEventListener("pointerdown",down);E.pads.appendChild(b)}}
async function hitPad(b,m,user=false){b.classList.add("hit");setTimeout(()=>b.classList.remove("hit","bad","target"),150);await playNote(m,.9,0,.55);state.last.push(m);state.last=state.last.slice(-16);if(state.loop)state.loopNotes.push({m,step:state.loopNotes.length%16});if(state.mode==="game"||state.mode==="train")checkGame(m,b);else setReadout(`${noteName(m)} · ${inst().name}`)}
function checkGame(m,b){const want=state.target[state.targetIndex];if(!Number.isFinite(want)){newGame();return}if(m===want){state.targetIndex++;state.score+=10+state.streak;state.streak++;b.classList.add("targetHit");if(state.targetIndex>=state.target.length){state.score+=50;setReadout("round clear · fakebot learns your hands");setTimeout(newGame,550)}}else{state.streak=0;state.score=Math.max(0,state.score-3);b.classList.add("bad");setReadout(`wanted ${noteName(want)} · heard ${noteName(m)}`)}syncScore();syncTargetDots()}
function generatePhrase(len=6,weird=false){const pads=padMidis();if(!pads.length)return[];let p=[],idx=Math.floor(pads.length/2);for(let i=0;i<len;i++){idx=clamp(idx+pick(weird?[-5,-3,-2,-1,1,2,3,5]:[-2,-1,0,1,2]),0,pads.length-1);p.push(pads[idx])}return p}
function newGame(){const len=state.mode==="train"?4:clamp(4+Math.floor(state.score/90),4,9);state.target=generatePhrase(len,state.mode==="game"&&Math.random()<.28);state.targetIndex=0;E.targetText.textContent=patternText(state.target);setReadout("listen, then play it back");syncTargetDots();playPhrase(state.target,.12)}
function playPhrase(p,gap=.16){p.forEach((m,i)=>setTimeout(()=>{const pad=$$(".pad").find(x=>Number(x.dataset.midi)===m);if(pad){pad.classList.add("target");setTimeout(()=>pad.classList.remove("target"),180)}playNote(m,.82,0,.45)},i*gap*1000))}
function nearestPad(m){const pads=padMidis();return pads.reduce((a,b)=>Math.abs(b-m)<Math.abs(a-m)?b:a,pads[0]||m)}
function botPhrase(mode="answer"){let base=state.last.length?state.last.slice(-6):generatePhrase(6);let p;if(mode==="copy")p=base;else if(mode==="simple")p=base.filter((_,i)=>i%2===0).map((m,i)=>i%2?m:degreeMidi(0));else if(mode==="weird")p=base.map((m,i)=>m+pick([-12,-7,-1,0,1,6,12])+(i%3===0?state.key:0));else p=base.slice().reverse().map((m,i)=>m+pick([-2,0,2,5])+(i===base.length-1?7:0));p=p.map(nearestPad);state.last=p;setReadout(`bot: ${patternText(p)}`);playPhrase(p,.14)}
function startLoop(){clearInterval(loopTimer);E.play.classList.add("active");state.loop=true;if(!state.loopNotes.length)state.loopNotes=generatePhrase(8).map((m,i)=>({m,step:i*2}));let step=0;const ms=60000/Number(state.tempo||96)/4;loopTimer=setInterval(()=>{state.loopNotes.filter(n=>n.step%16===step).forEach(n=>playNote(n.m,.72,0,.25));step=(step+1)%16},ms)}
function stopLoop(){state.loop=false;clearInterval(loopTimer);E.play.classList.remove("active")}function setMode(m){state.mode=m;["perf","game","train"].forEach(x=>$("#"+x+"Mode").classList.toggle("active",(x==="perf"?"perform":x)===m));setReadout(m==="perform"?"perform mode · tap pads + bot reply":m+" mode · match the target");if(m!=="perform")newGame()}
function fillControls(){KEYS.forEach((k,i)=>E.keySel.add(new Option(k,i)));Object.keys(SCALES).forEach(s=>E.scaleSel.add(new Option(s,s)));INSTR.forEach(x=>E.instSel.add(new Option(x.name,x.id)));E.keySel.value=state.key;E.scaleSel.value=state.scale;E.instSel.value=state.inst}
function bind(){E.keySel.onchange=()=>{state.key=Number(E.keySel.value);makePads();if(state.mode!=="perform")newGame()};E.scaleSel.onchange=()=>{state.scale=E.scaleSel.value;makePads();if(state.mode!=="perform")newGame()};E.instSel.onchange=()=>{state.inst=E.instSel.value;makePads();setReadout(inst().name)};E.tempo.onchange=()=>{state.tempo=clamp(Number(E.tempo.value)||96,50,220);if(state.loop)startLoop()};E.play.onclick=()=>state.loop?stopLoop():startLoop();E.reply.onclick=()=>botPhrase("answer");E.mutate.onclick=()=>{state.loopNotes=state.loopNotes.map(n=>({m:nearestPad(n.m+pick([-2,0,2,7,-7])),step:(n.step+pick([0,0,1,15]))%16}));botPhrase("weird")};E.newGame.onclick=newGame;E.panic.onclick=()=>{stopLoop();if(ctx)master.gain.setValueAtTime(.78,ctx.currentTime);setReadout("panic cleared")};$("#perfMode").onclick=()=>setMode("perform");$("#gameMode").onclick=()=>setMode("game");$("#trainMode").onclick=()=>setMode("train");$$(".botStrip button").forEach(b=>b.onclick=()=>botPhrase(b.dataset.action));document.addEventListener("visibilitychange",()=>{if(document.hidden)stopLoop()})}
fillControls();makePads();bind();syncScore();setReadout("Fakebot 2 ready · tap a pad");
})();
